services:
  backend:
    build: ./backend
    env_file:
      - .env
    command: fastapi run app/main.py --host ${BACKEND_HOST} --port 8000
    ports:
      - "${BACKEND_PORT}:8000"

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"

