DROP TABLE IF EXISTS participation_multi CASCADE;
DROP TABLE IF EXISTS participation CASCADE;
DROP TABLE IF EXISTS iteration CASCADE;
DROP TABLE IF EXISTS partie CASCADE;
DROP TABLE IF EXISTS tournoi_classique CASCADE;
DROP TABLE IF EXISTS tournoi_multi CASCADE;
DROP TABLE IF EXISTS tournoi CASCADE;
DROP TABLE IF EXISTS strategie CASCADE;

DROP TYPE IF EXISTS type_tournoi CASCADE;

DROP FUNCTION IF EXISTS supprimer_tournois_apres_suppression_strategie_classique() CASCADE;
DROP FUNCTION IF EXISTS supprimer_tournois_apres_suppression_strategie_multi() CASCADE;


CREATE TYPE type_tournoi AS ENUM ('Classique', 'Multi');

CREATE TABLE strategie (
    id_strategie BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(255) NOT NULL,
    explication TEXT NOT NULL,
    script_rhai TEXT NOT NULL,
    type_strategie type_tournoi NOT NULL
);

CREATE TABLE tournoi (
    id_tournoi BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_creation DATE NOT NULL,
    meilleure_strategie VARCHAR(255),
    type_tournoi type_tournoi NOT NULL
);

CREATE TABLE tournoi_classique (
    id_tournoi BIGINT PRIMARY KEY,
    nb_iterations INT NOT NULL,
    cout_coop_coop INT NOT NULL,
    cout_coop_trahi INT NOT NULL,
    cout_trahi_coop INT NOT NULL,
    cout_trahi_trahi INT NOT NULL,
    CONSTRAINT fk_tournoi_classique_tournoi FOREIGN KEY (id_tournoi) REFERENCES tournoi(id_tournoi) ON DELETE CASCADE
);

CREATE TABLE tournoi_multi (
    id_tournoi BIGINT PRIMARY KEY,
    duree_secondes SMALLINT NOT NULL,
    CONSTRAINT fk_tournoi_multi_tournoi FOREIGN KEY (id_tournoi) REFERENCES tournoi(id_tournoi) ON DELETE CASCADE
);

CREATE TABLE partie (
    id_partie BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_strategie_1 BIGINT NOT NULL,
    id_strategie_2 BIGINT NOT NULL,
    id_tournoi BIGINT NOT NULL,
    CONSTRAINT fk_partie_strategie_1 FOREIGN KEY (id_strategie_1) REFERENCES strategie(id_strategie) ON DELETE CASCADE,
    CONSTRAINT fk_partie_strategie_2 FOREIGN KEY (id_strategie_2) REFERENCES strategie(id_strategie) ON DELETE CASCADE,
    CONSTRAINT fk_partie_tournoi_classique FOREIGN KEY (id_tournoi) REFERENCES tournoi_classique(id_tournoi) ON DELETE CASCADE
);

CREATE TABLE iteration (
    id_iteration BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_partie BIGINT NOT NULL,
    numero_iteration INT NOT NULL,
    choix_strategie_1 BOOLEAN NOT NULL,
    choix_strategie_2 BOOLEAN NOT NULL,
    CONSTRAINT fk_iteration_partie FOREIGN KEY (id_partie) REFERENCES partie(id_partie) ON DELETE CASCADE
);

CREATE TABLE participation (
    id_tournoi BIGINT NOT NULL,
    id_strategie BIGINT NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (id_tournoi, id_strategie),
    CONSTRAINT fk_participation_tournoi_classique FOREIGN KEY (id_tournoi) REFERENCES tournoi_classique(id_tournoi) ON DELETE CASCADE,
    CONSTRAINT fk_participation_strategie FOREIGN KEY (id_strategie) REFERENCES strategie(id_strategie) ON DELETE CASCADE
);

CREATE TABLE participation_multi (
    id_tournoi BIGINT NOT NULL,
    id_strategie BIGINT NOT NULL,
    nombre_trahisons SMALLINT NOT NULL,
    nombre_cooperations SMALLINT NOT NULL,
    CONSTRAINT pk_participation_multi PRIMARY KEY (id_tournoi, id_strategie),
    CONSTRAINT fk_participation_multi_tournoi_multi FOREIGN KEY (id_tournoi) REFERENCES tournoi_multi(id_tournoi) ON DELETE CASCADE,
    CONSTRAINT fk_participation_strategie FOREIGN KEY (id_strategie) REFERENCES strategie(id_strategie) ON DELETE CASCADE
);

CREATE FUNCTION supprimer_tournois_apres_suppression_strategie_classique() RETURNS TRIGGER AS $supprimer_tournois_apres_suppression_strategie_classique$
    BEGIN
    DELETE FROM tournoi WHERE id_tournoi = OLD.id_tournoi;

    RETURN OLD;
    END;
$supprimer_tournois_apres_suppression_strategie_classique$ LANGUAGE plpgsql;

CREATE FUNCTION supprimer_tournois_apres_suppression_strategie_multi() RETURNS TRIGGER AS $supprimer_tournois_apres_suppression_strategie_multi$
    BEGIN
    DELETE FROM tournoi WHERE id_tournoi = OLD.id_tournoi;

    RETURN OLD;
    END;
$supprimer_tournois_apres_suppression_strategie_multi$ LANGUAGE plpgsql;

CREATE TRIGGER supprimer_tournois_apres_suppression_strategie_classique AFTER DELETE ON participation
    FOR EACH ROW EXECUTE PROCEDURE supprimer_tournois_apres_suppression_strategie_classique();

CREATE TRIGGER supprimer_tournois_apres_suppression_strategie_multi AFTER DELETE ON participation_multi
    FOR EACH ROW EXECUTE PROCEDURE supprimer_tournois_apres_suppression_strategie_multi();


-- Insertions

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Always cooperate', 'Always cooperate', 'return Choice::COOPERATE;', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Always betray', 'Always betray', 'return Choice::BETRAY;', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Random', 'Random', 'if rand(0,1)==0{return Choice::COOPERATE;} else{return Choice::BETRAY;};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Tit for tat', 'First cooperate, then subsequently replicate an opponent''s previous action', 'if len(last_current_strokes)==0{return Choice::COOPERATE;} else{ if last_current_strokes[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;}};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Grudger', 'Cooperate, but always betray if an opponent betray', 'for i in last_current_strokes{ if i==Choice::BETRAY.value{return Choice::BETRAY;}} return Choice::COOPERATE;', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Hesitant', 'Alternate cooperate and betray', 'if len(last_current_strokes)%2==0{return Choice::COOPERATE;}else{return Choice::BETRAY;};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Tideman & Chieruzzi', 'First cooperate, then subsequently replicate an opponent''s previous action but betray only if the opponent betray two times', 'if len(last_current_strokes)<3{return Choice::COOPERATE;}else{ if last_current_strokes[-1]==0{return Choice::COOPERATE;} else{ if last_current_strokes[-2]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Grofman', 'Start by cooperate, then use the last three turns', 'if len(last_current_strokes)<4{return Choice::COOPERATE;} else{ if last_current_strokes[-1] + last_current_strokes[-2] + last_current_strokes[-3]<2{return Choice::COOPERATE;} else{return Choice::BETRAY;}};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Shubik', 'Cooperate, but betray twenty times if an opponent betray', 'let punition_restante = 0;for i in 0..len(last_current_strokes) { if last_current_strokes[i] == Choice::BETRAY.value {punition_restante = 20;} if punition_restante > 0 {punition_restante -= 1;}}if punition_restante > 0 {return Choice::BETRAY;}return Choice::COOPERATE;', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Davis', 'Cooperate, but betray ten times if an opponent betray, and cooperate back only if no betray happenend since the previous one', 'let debut_punition = -1;for i in 0..len(last_current_strokes) { if last_current_strokes[i] == Choice::BETRAY.value {debut_punition = i;}}if debut_punition >= 0 { let tours_depuis = len(last_current_strokes) - debut_punition - 1; if tours_depuis < 10 {return Choice::BETRAY;}}return Choice::COOPERATE;', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('SteinRapoport', 'First cooperate, then subsequently replicate an opponent''s previous action, with a probability to cooperate', 'if len(last_current_strokes)==0{return Choice::COOPERATE;}else{ if rand(1,100)<10{return Choice::COOPERATE;} else { if last_current_strokes[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Joss', 'First cooperate, then subsequently replicate an opponent''s previous action, with a probability to betray', 'if len(last_current_strokes)==0{return Choice::COOPERATE;}else{ if rand(1,100)<10{return Choice::BETRAY;} else { if last_current_strokes[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};', 'Classique');

INSERT INTO strategie (nom, explication, script_rhai, type_strategie)
VALUES ('Feld', 'First cooperate, then subsequently replicate an opponent''s previous action, but always betray two times', 'if len(last_current_strokes)==0{return Choice::COOPERATE;}else{ if last_current_strokes[-1]==1 {return Choice::BETRAY;} else{ if len(last_current_strokes)>1 { if last_current_strokes[-2]==1{return Choice::BETRAY;} } }}return Choice::COOPERATE;', 'Classique');
