DROP TABLE IF EXISTS participation;
DROP TABLE IF EXISTS iteration;
DROP TABLE IF EXISTS partie;
DROP TABLE IF EXISTS tournoi;
DROP TABLE IF EXISTS strategie;


CREATE TABLE strategie (
    id_strategie BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(255) NOT NULL,
    explication TEXT NOT NULL,
    script_rhai TEXT NOT NULL
);

CREATE TABLE tournoi (
    id_tournoi BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nb_iterations INT NOT NULL,
    cout_coop_coop INT NOT NULL,
    cout_coop_trahi INT NOT NULL,
    cout_trahi_coop INT NOT NULL,
    cout_trahi_trahi INT NOT NULL,
    date_creation DATE NOT NULL,
    meilleure_strategie VARCHAR(255)
);

CREATE TABLE partie (
    id_partie BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_strategie_1 BIGINT NOT NULL,
    id_strategie_2 BIGINT NOT NULL,
    id_tournoi BIGINT NOT NULL,
    CONSTRAINT fk_id_strategie_1 FOREIGN KEY (id_strategie_1) REFERENCES strategie(id_strategie) ON DELETE CASCADE,
    CONSTRAINT fk_id_strategie_2 FOREIGN KEY (id_strategie_2) REFERENCES strategie(id_strategie) ON DELETE CASCADE,
    CONSTRAINT fk_id_tournoi FOREIGN KEY (id_tournoi) REFERENCES tournoi(id_tournoi) ON DELETE CASCADE
);

CREATE TABLE iteration (
    id_iteration BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_partie BIGINT NOT NULL,
    numero_iteration INT NOT NULL,
    choix_strategie_1 BOOLEAN NOT NULL,
    choix_strategie_2 BOOLEAN NOT NULL,
    CONSTRAINT fk_id_partie FOREIGN KEY (id_partie) REFERENCES partie(id_partie) ON DELETE CASCADE
);

CREATE TABLE participation (
    id_tournoi BIGINT NOT NULL,
    id_strategie BIGINT NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (id_tournoi, id_strategie),
    CONSTRAINT fk_id_tournoi FOREIGN KEY (id_tournoi) REFERENCES tournoi(id_tournoi) ON DELETE CASCADE,
    CONSTRAINT fk_id_strategie FOREIGN KEY (id_strategie) REFERENCES strategie(id_strategie) ON DELETE CASCADE
);

CREATE FUNCTION supprimer_tournois_apres_suppression_strategie() RETURNS TRIGGER AS $supprimer_tournois_apres_suppression_strategie$
    BEGIN
    DELETE FROM tournoi WHERE id_tournoi = OLD.id_tournoi;

    RETURN OLD;
    END;
$supprimer_tournois_apres_suppression_strategie$ LANGUAGE plpgsql;

CREATE TRIGGER supprimer_tournois_apres_suppression_strategie AFTER DELETE ON participation
    FOR EACH ROW EXECUTE PROCEDURE supprimer_tournois_apres_suppression_strategie();

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Always cooperate', 'Always cooperate', 'return Choice::COOPERATE;');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Always betray', 'Always betray', 'return Choice::BETRAY;');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Random', 'Random', 'if rand(0,1)==0{return Choice::COOPERATE;} else{return Choice::BETRAY;};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Tit for tat', 'First cooperate, then subsequently replicate an opponent''s previous action', 'if len(derniers_coups_strategie_adverse)==0{return Choice::COOPERATE;} else{ if derniers_coups_strategie_adverse[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;}};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Grudger', 'Cooperate, but always betray if an opponent betray', 'for i in derniers_coups_strategie_adverse{ if i==Choice::BETRAY.value{return Choice::BETRAY;}} return Choice::COOPERATE;');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Hesitant', 'Alternate cooperate and betray', 'if len(derniers_coups_strategie_adverse)%2==0{return Choice::COOPERATE;}else{return Choice::BETRAY;};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Tideman & Chieruzzi', 'First cooperate, then subsequently replicate an opponent''s previous action but betray only if the opponent betray two times', 'if len(derniers_coups_strategie_adverse)<3{return Choice::COOPERATE;}else{ if derniers_coups_strategie_adverse[-1]==0{return Choice::COOPERATE;} else{ if derniers_coups_strategie_adverse[-2]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Grofman', 'Start by cooperate, then use the last three turns', 'if len(derniers_coups_strategie_adverse)<4{return Choice::COOPERATE;} else{ if derniers_coups_strategie_adverse[-1] + derniers_coups_strategie_adverse[-2] + derniers_coups_strategie_adverse[-3]<2{return Choice::COOPERATE;} else{return Choice::BETRAY;}};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Shubik', 'Cooperate, but betray twenty times if an opponent betray', 'let punition_restante = 0;for i in 0..len(derniers_coups_strategie_adverse) { if derniers_coups_strategie_adverse[i] == Choice::BETRAY.value {punition_restante = 20;} if punition_restante > 0 {punition_restante -= 1;}}if punition_restante > 0 {return Choice::BETRAY;}return Choice::COOPERATE;');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Davis', 'Cooperate, but betray ten times if an opponent betray, and cooperate back only if no betray happenend since the previous one', 'let debut_punition = -1;for i in 0..len(derniers_coups_strategie_adverse) { if derniers_coups_strategie_adverse[i] == Choice::BETRAY.value {debut_punition = i;}}if debut_punition >= 0 { let tours_depuis = len(derniers_coups_strategie_adverse) - debut_punition - 1; if tours_depuis < 10 {return Choice::BETRAY;}}return Choice::COOPERATE;');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('SteinRapoport', 'First cooperate, then subsequently replicate an opponent''s previous action, with a probability to cooperate', 'if len(derniers_coups_strategie_adverse)==0{return Choice::COOPERATE;}else{ if rand(1,100)<10{return Choice::COOPERATE;} else { if derniers_coups_strategie_adverse[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Joss', 'First cooperate, then subsequently replicate an opponent''s previous action, with a probability to betray', 'if len(derniers_coups_strategie_adverse)==0{return Choice::COOPERATE;}else{ if rand(1,100)<10{return Choice::BETRAY;} else { if derniers_coups_strategie_adverse[-1]==Choice::COOPERATE.value{return Choice::COOPERATE;} else{return Choice::BETRAY;} }};');

INSERT INTO strategie (nom, explication, script_rhai)
VALUES ('Feld', 'First cooperate, then subsequently replicate an opponent''s previous action, but always betray two times', 'if len(derniers_coups_strategie_adverse)==0{return Choice::COOPERATE;}else{ if derniers_coups_strategie_adverse[-1]==1 {return Choice::BETRAY;} else{ if len(derniers_coups_strategie_adverse)>1 { if derniers_coups_strategie_adverse[-2]==1{return Choice::BETRAY;} } }}return Choice::COOPERATE;');
